### ISSUE TITLE
make handlebar template for administration page to review/accept/deny pending user requests to join projects

### ISSUE THREAD

**Issue by GabrielRStella** [rohitmucherla/projectSubmission#15]

**Comment by vikaspotluri123** [comment]
@XyPhoGR Can deny be delete? As in delete the user?

**Comment by GabrielRStella** [comment]
No, the user does not get removed from the system. Only their application to that project is denied.

**Comment by vikaspotluri123** [comment]
Whoops, I goofed! I was working on displaying users (as in all users), instead of projects because I can't read properly.

**Comment by vikaspotluri123** [comment]
Completed w/  f094905
