### ISSUE TITLE
For Review Section

### ISSUE THREAD

**Issue by rohitmucherla** [rohitmucherla/projectSubmission#30]
I think there should be a  for review section on the admin panel - essentially reducing the number of clicks required to get to a place like that

**Comment by vikaspotluri123** [comment]
This should be done. There was an issue with wording for projects (see f68d11b), but users and applications are ready.

When you go to the admin panel (click `Admin panel` in the header), each category card has 2 links - the first is the "Everything" link which shows both approved / unapproved [category], and the second is the unapproved link which shows unapproved [category]s
