### ISSUE TITLE
Rename Applications

### ISSUE THREAD

**Issue by rohitmucherla** [rohitmucherla/projectSubmission#31]
I think we should rename applications to perhaps be something like "Project Approvals". I think it's a little more intuitive up front

**Comment by vikaspotluri123** [comment]
The `applications` link is visible to all logged in users and shows their application to be added to a specific project, if they have any. For example, if a user is interested in 3 projects, they can apply to all 3, outlining why they want to be a part of the project and whatnot. Later, if the user wants to view their applications, they can click that link and view what they said, as well as edit if necessary
