### ISSUE TITLE
Add a name section to the application

### ISSUE THREAD

**Issue by rohitmucherla** [rohitmucherla/projectSubmission#32]
So im not 100% sure on this one but I had sent a test application as myself but since I don't have any other test ones, I wasn't sure if I can see the name if it's not mine, whereas if it is it doesn't show it. Can we just default it to have the name on the application?

**Comment by vikaspotluri123** [comment]
@rohitmucherla I hadn't committed a few routes 😆 I made some changes to what I hadn't committed and I think everything should work 😄
